name: ad_scz_env
channels:
  - defaults
  - conda-forge
  - bioconda
dependencies:
  - python=3.9
  - pip
  - pandas>=1.3
  - numpy>=1.20
  - scikit-learn>=1.0
  - xgboost>=1.5
  - matplotlib>=3.4
  - seaborn>=0.11
  - pytorch>=1.10
  - pytorch-tabnet>=3.1
  - plink
  - ucsc-liftover
